---
apiVersion: v1
kind: Namespace
metadata:
  name: meet
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meet
  name: meet
  namespace: meet
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: meet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet
  name: meet
  namespace: meet
spec:
  selector:
    matchLabels:
      app: meet
  template:
    metadata:
      labels:
        app: meet
    spec:
      containers:
      - image: julia/redirect:latest
        imagePullPolicy: Always
        name: meet
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: https
  labels:
    app: meet
  name: meet
  namespace: meet
spec:
  rules:
  - host: meet.jul.run
    http:
      paths:
      - backend:
          service:
            name: meet
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - meet.jul.run
    secretName: meet-https-cert
